import type { NextPage } from 'next'
import { useRouter } from 'next/router';
import Head from 'next/head'
import MainLayout from '@components/layout/MainLayout'
import Row from '@components/layout/RowLayout'
import Navigation from '@components/common/Navigation'
import Content from '@components/common/Content'

const Home: NextPage = () => {
  const router = useRouter();

  const LoginClick = (e: React.MouseEvent<HTMLButtonElement, MouseEvent>) => {
    e.preventDefault()
    router.push('/dashboard')
  }
  return (
    <>
      <Head>
        <title>Kugue Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel='stylesheet'
          href='https://fonts.googleapis.com/css2?family=Inter:wght@100;300;500;700&display=swap'
        />
      </Head>
      <MainLayout>
        <Row>
          <Navigation />
          <Content />
        </Row>
      </MainLayout>
    </>
  )
}

export default Home
