import type { NextPage } from 'next'
import { useRouter } from 'next/router';
import Head from 'next/head'
import styled from 'styled-components'
import Button from '@components/common/Button'
import LoginLayout from '@components/layout/LoginLayout'
import GlassCard from '@components/common/GlassCard'

const Title = styled.h1`
  color: var(--text-primary);
`

const Home: NextPage = () => {
  const router = useRouter();

  const LoginClick = (e: React.MouseEvent<HTMLButtonElement, MouseEvent>) => {
    e.preventDefault()
    router.push('/dashboard')
  }
  return (
    <LoginLayout>
      <Head>
        <title>Re-Group-Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title>ようこそ、技大祭へ</Title>
      <Button
        width={ "150px" }
        height={ "40px" }
        onClick={ LoginClick }
      >Login</Button>
    </LoginLayout>
  )
}

export default Home
